### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by upbeatDiamond** [Pocket-Godot/Palette-Shininess#1]
What license is this under, or would be under? 

May I use it in a free open source work with attribution? If so, how would you like to be credited?

**Comment by mechPenSketch** [comment]
To be honest, I don't know what to put for licensing when it comes to fan works. Maybe on your `README.md`, you could add a link to this repo?

**Comment by mechPenSketch** [comment]
After reading through licensing in github, I've decided to give this repo mit. Not having any licenses implies that a work may not be used by others, which defeats the purpose of making my repos public.
